//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGII_PFD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFD_ROLES
    {
        public PFD_ROLES()
        {
            this.PFD_PROCEDIMIENTOS = new HashSet<PFD_PROCEDIMIENTOS>();
            this.PFD_USUARIOS = new HashSet<PFD_USUARIOS>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<PFD_PROCEDIMIENTOS> PFD_PROCEDIMIENTOS { get; set; }
        public virtual ICollection<PFD_USUARIOS> PFD_USUARIOS { get; set; }
    }
}
