//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGII_PFD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFD_PROCEDIMIENTOS
    {
        public PFD_PROCEDIMIENTOS()
        {
            this.PFD_PARAMETROS = new HashSet<PFD_PARAMETROS>();
            this.PFD_ROLES = new HashSet<PFD_ROLES>();
            this.PFD_LOG = new HashSet<PFD_LOG>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string PROCEDIMIENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal HABILITADO { get; set; }
        public short ESTANDARIZADO { get; set; }
    
        public virtual ICollection<PFD_PARAMETROS> PFD_PARAMETROS { get; set; }
        public virtual ICollection<PFD_ROLES> PFD_ROLES { get; set; }
        public virtual ICollection<PFD_LOG> PFD_LOG { get; set; }
    }
}
