//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGII_PFD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFD_LOG
    {
        public decimal ID { get; set; }
        public decimal ID_USUARIO { get; set; }
        public decimal ID_PROCEDIMIENTO { get; set; }
        public decimal CODIGO_RESPUESTA { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual PFD_PROCEDIMIENTOS PFD_PROCEDIMIENTOS { get; set; }
        public virtual PFD_USUARIOS PFD_USUARIOS { get; set; }
    }
}
