//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEC.Reports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SIGECEntities : DbContext
    {
        public SIGECEntities()
            : base("name=SIGECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<PrintAnalysisIndication_Result> PrintAnalysisIndication(Nullable<int> cons_ID)
        {
            var cons_IDParameter = cons_ID.HasValue ?
                new ObjectParameter("cons_ID", cons_ID) :
                new ObjectParameter("cons_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrintAnalysisIndication_Result>("PrintAnalysisIndication", cons_IDParameter);
        }
    
        public virtual ObjectResult<PrintProcedureIndication_Result> PrintProcedureIndication(Nullable<int> cons_ID)
        {
            var cons_IDParameter = cons_ID.HasValue ?
                new ObjectParameter("cons_ID", cons_ID) :
                new ObjectParameter("cons_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrintProcedureIndication_Result>("PrintProcedureIndication", cons_IDParameter);
        }
    
        public virtual ObjectResult<PrintStudyIndication_Result> PrintStudyIndication(Nullable<int> cons_ID)
        {
            var cons_IDParameter = cons_ID.HasValue ?
                new ObjectParameter("cons_ID", cons_ID) :
                new ObjectParameter("cons_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrintStudyIndication_Result>("PrintStudyIndication", cons_IDParameter);
        }
    
        public virtual ObjectResult<PrintPrescription_Result> PrintPrescription(Nullable<int> cons_ID)
        {
            var cons_IDParameter = cons_ID.HasValue ?
                new ObjectParameter("cons_ID", cons_ID) :
                new ObjectParameter("cons_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrintPrescription_Result>("PrintPrescription", cons_IDParameter);
        }
    
        public virtual ObjectResult<PrintIncomes_Result> PrintIncomes(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrintIncomes_Result>("PrintIncomes", dateParameter);
        }
    }
}
